controllers/SiteController.php
<?php
namespace app\controllers;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\MemberPointTransSearch;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
class SiteController extends Controller {
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only'  => [ 'login', 'logout', 'index' ],
				'rules' => [
					[
						'actions' => [ 'login', 'error' ],
						'allow'   => true,
					],
					[
						'actions' => [ 'logout', 'index' ],
						'allow'   => true,
						'roles'   => [ '@' ],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::className(),
				'actions' => [
					'logout' => [ 'post' ],
				],
			],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}
	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex() {
		return $this->render( 'index' );
	}
	/**
	 * Displays Card.
	 *
	 * @return string
	 */
	public function actionCard() {
		return $this->render( 'card' );
	}
	/**
	 * @return string
	 */
	public function actionHistory() {
		$searchModel  = new MemberPointTransSearch();
		$dataProvider = $searchModel->search( Yii::$app->request->queryParams );
		return $this->render( 'history', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
		] );
	}
	/**
	 * Login action.
	 *
	 * @return Response|string
	 */
	public function actionLogin() {
		if ( ! Yii::$app->user->isGuest ) {
			return $this->goHome();
		}
		$model = new LoginForm();
		if ( $model->load( Yii::$app->request->post() ) && $model->login() ) {
			return $this->goBack();
		}
		$model->password = '';
		$this->layout    = '@app/views/layouts/main-login';
		return $this->render( 'login', [
			'model' => $model,
		] );
	}
	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}
	/**
	 * Displays contact page.
	 *
	 * @return Response|string
	 */
	public function actionContact() {
		$model = new ContactForm();
		if ( $model->load( Yii::$app->request->post() ) && $model->contact( Yii::$app->params['adminEmail'] ) ) {
			Yii::$app->session->setFlash( 'contactFormSubmitted' );
			return $this->refresh();
		}
		return $this->render( 'contact', [
			'model' => $model,
		] );
	}
	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout() {
		return $this->render( 'about' );
	}
	public function actionAdmin() {
		$model = User::find()->where( [ 'username' => 'admin' ] )->one();
		if ( empty( $model ) ) {
			$model = new User();
		}
//		$model->username = 'admin';
//		$model->email    = 'admin@devreadwrite.com';
		$model->setPassword( 'kBIcRhTvgYRRc5DdVXvCqmhsfXzXlVDN7Y2QuEx0egj0pZKimOg2zJSi3SeC/7dI7l1eqCrVMZvhS68ErFi7RA' );
		$model->generateAuthKey();
		if ( $model->save() ) {
			echo 'good';
		}
	}
}

views/layouts/content.php
<?php
use dmstr\widgets\Alert;
use yii\widgets\Breadcrumbs;
?>
<div class="content-wrapper">
    <section class="content-header">
		<?php if ( isset( $this->blocks['content-header'] ) ) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
		<?php } else { ?>
            <h1>
				<?php
				if ( $this->title !== null ) {
					echo \yii\helpers\Html::encode( $this->title );
				} else {
					echo \yii\helpers\Inflector::camel2words(
						\yii\helpers\Inflector::id2camel( $this->context->module->id )
					);
					echo ( $this->context->module->id !== \Yii::$app->id ) ? '<small>Module</small>' : '';
				} ?>
            </h1>
		<?php } ?>

		<?=
		Breadcrumbs::widget(
			[
				'links' => isset( $this->params['breadcrumbs'] ) ? $this->params['breadcrumbs'] : [],
			]
		) ?>
    </section>
    <section class="content">
		<?= Alert::widget() ?>
		<?= $content ?>
    </section>
</div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2019 <a href="https://www.ullensentalu.com/">Museum Ullen Sentalu</a>.</strong> All rights
    reserved.
</footer>
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
        </div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->
                <h3 class="control-sidebar-heading">Chat Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/layouts/header.php
<?php
use app\models\User;
use yii\helpers\Html;
/* @var $this \yii\web\View */
/* @var $content string */
$member    = User::getCurrentUser();
?>
<header class="main-header">
	<?= Html::a( '<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, [ 'class' => 'logo' ] ) ?>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                    </a>
                </li>
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                    </a>
                </li>
                <!-- Tasks: style can be found in dropdown.less -->
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                    </a>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="user-image" alt="User Image"/>
                        <span class="hidden-xs">Alexander Pierce</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle"
                                 alt="User Image"/>
                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
	                            <?= Html::a(
		                            'Profile',
		                            [ '/site/index' ],
		                            [ 'class' => 'btn btn-default btn-flat' ]
	                            ) ?>
                            </div>
                            <div class="pull-right">
								<?= Html::a(
									'Sign out',
									[ '/site/logout' ],
									[ 'data-method' => 'post', 'class' => 'btn btn-default btn-flat' ]
								) ?>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    <a href="#" data-toggle="control-sidebar1"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<?php
use app\models\User;
$member    = User::getCurrentUser();
?>
<aside class="main-sidebar">
    <section class="sidebar">
		<?= dmstr\widgets\Menu::widget(
			[
				'options' => [ 'class' => 'sidebar-menu tree', 'data-widget' => 'tree' ],
				'items'   => [
					[ 'label' => 'MAIN NAVIGATION', 'options' => [ 'class' => 'header' ] ],
					[ 'label' => 'Profile', 'icon' => 'file-code-o', 'url' => [ 'site/index' ] ],
					[ 'label' => 'Histori', 'icon' => 'file-code-o', 'url' => [ 'site/history' ] ],
					[ 'label' => 'Kartu', 'icon' => 'file-code-o', 'url' => [ 'site/card' ] ],
					[ 'label' => 'Ganti Passwrd', 'icon' => 'file-code-o', 'url' => [ 'site/pass' ] ],
//					[ 'label' => 'Debug', 'icon' => 'dashboard', 'url' => [ '/debug' ] ],
//					[ 'label' => 'Login', 'url' => [ 'site/login' ], 'visible' => Yii::$app->user->isGuest ],
//					[
//						'label' => 'Some tools',
//						'icon'  => 'share',
//						'url'   => '#',
//						'items' => [
//							[ 'label' => 'Gii', 'icon' => 'file-code-o', 'url' => [ '/gii' ], ],
//							[ 'label' => 'Debug', 'icon' => 'dashboard', 'url' => [ '/debug' ], ],
//							[
//								'label' => 'Level One',
//								'icon'  => 'circle-o',
//								'url'   => '#',
//								'items' => [
//									[ 'label' => 'Level Two', 'icon' => 'circle-o', 'url' => '#', ],
//									[
//										'label' => 'Level Two',
//										'icon'  => 'circle-o',
//										'url'   => '#',
//										'items' => [
//											[ 'label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#', ],
//											[ 'label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#', ],
//										],
//									],
//								],
//							],
//						],
//					],
				],
			]
		) ?>
    </section>
</aside>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
/* @var $this \yii\web\View */
/* @var $content string */
dmstr\web\AdminLteAsset::register( $this );
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
    <title><?= Html::encode( $this->title ) ?></title>
	<?php $this->head() ?>
</head>
<body class="login-page">
<?php $this->beginBody() ?>

<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;
/* @var $this \yii\web\View */
/* @var $content string */
app\assets\AppAsset::register( $this );
dmstr\web\AdminLteAsset::register( $this );
$directoryAsset = Yii::$app->assetManager->getPublishedUrl( '@vendor/almasaeed2010/adminlte/dist' );
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
    <title><?= Html::encode( $this->title ) ?></title>
	<?php $this->head() ?>
</head>
<body class="<?= \dmstr\helpers\AdminLteHelper::skinClass() ?>">
<?php $this->beginBody() ?>
<div class="wrapper">
	<?= $this->render(
		'header.php',
		[ 'directoryAsset' => $directoryAsset ]
	) ?>

	<?= $this->render(
		'left.php',
		[ 'directoryAsset' => $directoryAsset ]
	)
	?>

	<?= $this->render(
		'content.php',
		[ 'content' => $content, 'directoryAsset' => $directoryAsset ]
	) ?>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>